[package]
name = "utf8char"
version = "0.1.0"
edition = "2021"

[[bench]]
harness = false
name = "default"

[dev-dependencies]
criterion = "0.5"
encode_unicode = "1.0.0"
rayon = "1.10.0"

[dependencies]

[profile.dev]
opt-level = 1
