//! Enums that are used by the internal representation of Utf8Char

/// Enum representing every valid state of the first byte of a utf8 encoded codepoint
#[repr(u8)]
// The ascii variants were copied over from the rust standard library
pub(crate) enum Utf8FirstByte {
    /// U+0000 (The default variant)
    Null = 0,
    /// U+0001
    StartOfHeading = 1,
    /// U+0002
    StartOfText = 2,
    /// U+0003
    EndOfText = 3,
    /// U+0004
    EndOfTransmission = 4,
    /// U+0005
    Enquiry = 5,
    /// U+0006
    Acknowledge = 6,
    /// U+0007
    Bell = 7,
    /// U+0008
    Backspace = 8,
    /// U+0009
    CharacterTabulation = 9,
    /// U+000A
    LineFeed = 10,
    /// U+000B
    LineTabulation = 11,
    /// U+000C
    FormFeed = 12,
    /// U+000D
    CarriageReturn = 13,
    /// U+000E
    ShiftOut = 14,
    /// U+000F
    ShiftIn = 15,
    /// U+0010
    DataLinkEscape = 16,
    /// U+0011
    DeviceControlOne = 17,
    /// U+0012
    DeviceControlTwo = 18,
    /// U+0013
    DeviceControlThree = 19,
    /// U+0014
    DeviceControlFour = 20,
    /// U+0015
    NegativeAcknowledge = 21,
    /// U+0016
    SynchronousIdle = 22,
    /// U+0017
    EndOfTransmissionBlock = 23,
    /// U+0018
    Cancel = 24,
    /// U+0019
    EndOfMedium = 25,
    /// U+001A
    Substitute = 26,
    /// U+001B
    Escape = 27,
    /// U+001C
    InformationSeparatorFour = 28,
    /// U+001D
    InformationSeparatorThree = 29,
    /// U+001E
    InformationSeparatorTwo = 30,
    /// U+001F
    InformationSeparatorOne = 31,
    /// U+0020
    Space = 32,
    /// U+0021
    ExclamationMark = 33,
    /// U+0022
    QuotationMark = 34,
    /// U+0023
    NumberSign = 35,
    /// U+0024
    DollarSign = 36,
    /// U+0025
    PercentSign = 37,
    /// U+0026
    Ampersand = 38,
    /// U+0027
    Apostrophe = 39,
    /// U+0028
    LeftParenthesis = 40,
    /// U+0029
    RightParenthesis = 41,
    /// U+002A
    Asterisk = 42,
    /// U+002B
    PlusSign = 43,
    /// U+002C
    Comma = 44,
    /// U+002D
    HyphenMinus = 45,
    /// U+002E
    FullStop = 46,
    /// U+002F
    Solidus = 47,
    /// U+0030
    Digit0 = 48,
    /// U+0031
    Digit1 = 49,
    /// U+0032
    Digit2 = 50,
    /// U+0033
    Digit3 = 51,
    /// U+0034
    Digit4 = 52,
    /// U+0035
    Digit5 = 53,
    /// U+0036
    Digit6 = 54,
    /// U+0037
    Digit7 = 55,
    /// U+0038
    Digit8 = 56,
    /// U+0039
    Digit9 = 57,
    /// U+003A
    Colon = 58,
    /// U+003B
    Semicolon = 59,
    /// U+003C
    LessThanSign = 60,
    /// U+003D
    EqualsSign = 61,
    /// U+003E
    GreaterThanSign = 62,
    /// U+003F
    QuestionMark = 63,
    /// U+0040
    CommercialAt = 64,
    /// U+0041
    CapitalA = 65,
    /// U+0042
    CapitalB = 66,
    /// U+0043
    CapitalC = 67,
    /// U+0044
    CapitalD = 68,
    /// U+0045
    CapitalE = 69,
    /// U+0046
    CapitalF = 70,
    /// U+0047
    CapitalG = 71,
    /// U+0048
    CapitalH = 72,
    /// U+0049
    CapitalI = 73,
    /// U+004A
    CapitalJ = 74,
    /// U+004B
    CapitalK = 75,
    /// U+004C
    CapitalL = 76,
    /// U+004D
    CapitalM = 77,
    /// U+004E
    CapitalN = 78,
    /// U+004F
    CapitalO = 79,
    /// U+0050
    CapitalP = 80,
    /// U+0051
    CapitalQ = 81,
    /// U+0052
    CapitalR = 82,
    /// U+0053
    CapitalS = 83,
    /// U+0054
    CapitalT = 84,
    /// U+0055
    CapitalU = 85,
    /// U+0056
    CapitalV = 86,
    /// U+0057
    CapitalW = 87,
    /// U+0058
    CapitalX = 88,
    /// U+0059
    CapitalY = 89,
    /// U+005A
    CapitalZ = 90,
    /// U+005B
    LeftSquareBracket = 91,
    /// U+005C
    ReverseSolidus = 92,
    /// U+005D
    RightSquareBracket = 93,
    /// U+005E
    CircumflexAccent = 94,
    /// U+005F
    LowLine = 95,
    /// U+0060
    GraveAccent = 96,
    /// U+0061
    SmallA = 97,
    /// U+0062
    SmallB = 98,
    /// U+0063
    SmallC = 99,
    /// U+0064
    SmallD = 100,
    /// U+0065
    SmallE = 101,
    /// U+0066
    SmallF = 102,
    /// U+0067
    SmallG = 103,
    /// U+0068
    SmallH = 104,
    /// U+0069
    SmallI = 105,
    /// U+006A
    SmallJ = 106,
    /// U+006B
    SmallK = 107,
    /// U+006C
    SmallL = 108,
    /// U+006D
    SmallM = 109,
    /// U+006E
    SmallN = 110,
    /// U+006F
    SmallO = 111,
    /// U+0070
    SmallP = 112,
    /// U+0071
    SmallQ = 113,
    /// U+0072
    SmallR = 114,
    /// U+0073
    SmallS = 115,
    /// U+0074
    SmallT = 116,
    /// U+0075
    SmallU = 117,
    /// U+0076
    SmallV = 118,
    /// U+0077
    SmallW = 119,
    /// U+0078
    SmallX = 120,
    /// U+0079
    SmallY = 121,
    /// U+007A
    SmallZ = 122,
    /// U+007B
    LeftCurlyBracket = 123,
    /// U+007C
    VerticalLine = 124,
    /// U+007D
    RightCurlyBracket = 125,
    /// U+007E
    Tilde = 126,
    /// U+007F
    Delete = 127,

    /// Begin outside of ascii range
    /// Generated by python script utf8firstbyte.py
    _128 = 0b10000000,
    _129 = 0b10000001,
    _130 = 0b10000010,
    _131 = 0b10000011,
    _132 = 0b10000100,
    _133 = 0b10000101,
    _134 = 0b10000110,
    _135 = 0b10000111,
    _136 = 0b10001000,
    _137 = 0b10001001,
    _138 = 0b10001010,
    _139 = 0b10001011,
    _140 = 0b10001100,
    _141 = 0b10001101,
    _142 = 0b10001110,
    _143 = 0b10001111,
    _144 = 0b10010000,
    _145 = 0b10010001,
    _146 = 0b10010010,
    _147 = 0b10010011,
    _148 = 0b10010100,
    _149 = 0b10010101,
    _150 = 0b10010110,
    _151 = 0b10010111,
    _152 = 0b10011000,
    _153 = 0b10011001,
    _154 = 0b10011010,
    _155 = 0b10011011,
    _156 = 0b10011100,
    _157 = 0b10011101,
    _158 = 0b10011110,
    _159 = 0b10011111,
    _160 = 0b10100000,
    _161 = 0b10100001,
    _162 = 0b10100010,
    _163 = 0b10100011,
    _164 = 0b10100100,
    _165 = 0b10100101,
    _166 = 0b10100110,
    _167 = 0b10100111,
    _168 = 0b10101000,
    _169 = 0b10101001,
    _170 = 0b10101010,
    _171 = 0b10101011,
    _172 = 0b10101100,
    _173 = 0b10101101,
    _174 = 0b10101110,
    _175 = 0b10101111,
    _176 = 0b10110000,
    _177 = 0b10110001,
    _178 = 0b10110010,
    _179 = 0b10110011,
    _180 = 0b10110100,
    _181 = 0b10110101,
    _182 = 0b10110110,
    _183 = 0b10110111,
    _184 = 0b10111000,
    _185 = 0b10111001,
    _186 = 0b10111010,
    _187 = 0b10111011,
    _188 = 0b10111100,
    _189 = 0b10111101,
    _190 = 0b10111110,
    _191 = 0b10111111,
    _192 = 0b11000000,
    _193 = 0b11000001,
    _194 = 0b11000010,
    _195 = 0b11000011,
    _196 = 0b11000100,
    _197 = 0b11000101,
    _198 = 0b11000110,
    _199 = 0b11000111,
    _200 = 0b11001000,
    _201 = 0b11001001,
    _202 = 0b11001010,
    _203 = 0b11001011,
    _204 = 0b11001100,
    _205 = 0b11001101,
    _206 = 0b11001110,
    _207 = 0b11001111,
    _208 = 0b11010000,
    _209 = 0b11010001,
    _210 = 0b11010010,
    _211 = 0b11010011,
    _212 = 0b11010100,
    _213 = 0b11010101,
    _214 = 0b11010110,
    _215 = 0b11010111,
    _216 = 0b11011000,
    _217 = 0b11011001,
    _218 = 0b11011010,
    _219 = 0b11011011,
    _220 = 0b11011100,
    _221 = 0b11011101,
    _222 = 0b11011110,
    _223 = 0b11011111,
    _224 = 0b11100000,
    _225 = 0b11100001,
    _226 = 0b11100010,
    _227 = 0b11100011,
    _228 = 0b11100100,
    _229 = 0b11100101,
    _230 = 0b11100110,
    _231 = 0b11100111,
    _232 = 0b11101000,
    _233 = 0b11101001,
    _234 = 0b11101010,
    _235 = 0b11101011,
    _236 = 0b11101100,
    _237 = 0b11101101,
    _238 = 0b11101110,
    _239 = 0b11101111,
    _240 = 0b11110000,
    _241 = 0b11110001,
    _242 = 0b11110010,
    _243 = 0b11110011,
    _244 = 0b11110100,
    _245 = 0b11110101,
    _246 = 0b11110110,
    _247 = 0b11110111,
}
